### ISSUE TITLE
HTTP agent borks on "system_profiler -detailLevel basic" TTP

### ISSUE THREAD

**Issue by privateducky** [preludeorg/pneuma#13]
Our "system_profiler -detailLevel basic" (MacOS) TTP breaks the HTTP Pneuma agent. Works fine on TCP.

**Comment by khyberspache** [comment]
Can you elaborate on breaks? Causes it to hang?

**Comment by khyberspache** [comment]
Got a repro - this is the error:
`2021/01/06 14:55:11 Post "http://127.0.0.1:3391": EOF`

Looks like the response beacon is too large. Will require tweaks to pneuma and operator's listening post.

**Comment by khyberspache** [comment]
This will be fixed in 0.9.13.  A bug on operator HTTP listener was preventing large data from being handled server side.  Resolved with the resolution of this: https://github.com/preludeorg/operator-support/issues/54
