### ISSUE TITLE
'go run main.go' not working out of box

### ISSUE THREAD

**Issue by CrimsonK1ng** [preludeorg/pneuma#4]
I am currently running into an issue when running go run && go build for pneuma. In the docs it mentions that you should just clone and use ```go run main.go <args>```

```
go run main.go -contact http -address http://127.0.0.1:3391
build command-line-arguments: cannot find module for path _/C_/Users/username/Documents/Tools/pneuma/commands

go build
main.go:4:2: local import "./sockets" in non-local package
main.go:5:2: local import "./util" in non-local package
```

Instead using go.mod with a replace for the import statements like:

```
module pneuma
go 1.15
replace github.com/preludeorg/pneuma => ./
require github.com/preludeorg/pneuma v0.0.0-00010101000000-000000000000
```

and switching all imports to using the full URI:

```
github.com/preludeorg/pneuma/sockets
```

allows me to successfully run the pneuma agent.

For reference I am using 
* ```go version go1.15.3 windows/amd64``` on windows
* ```go version go1.15.2 darwin/amd64``` on mac

**Comment by privateducky** [comment]
This is interesting. @khyberspache are you familiar with the reason on this?

**Comment by privateducky** [comment]
I was previously running (MacOS) on Go v1.14.6 darwin/amd64 with no issues. I upgraded to v1.15.2 to match this issue and still no issues. 

This leads me to believe the issue is related to the GoLang environment itself on the computer(s). We'll keep digging on this.

**Comment by CrimsonK1ng** [comment]
I did try setting this up on another system I own. I tried two other methods of installing:
1. Install via **go get** which resulted in 
```
unexpected directory layout:
	import path: _/homedir/go/src/github.com/preludeorg/pneuma/commands
	root: /homedir/go/src
	dir: /homedir/go/src/github.com/preludeorg/pneuma/commands
	expand root: /homedir/go
	expand dir: /homedir/go/src/github.com/preludeorg/pneuma/commands
	separator: /
```
2. Manual install under $GOPATH/github.com/preludeorg/pneuma which resulted in the same error above.
3. Clone into directory outside of $GOPATH and initialization via **go mod** which results in the original error in the first post.

For reference my $GOPATH is set to the default location. 
```
GOPATH=/homedir/go
GOBIN=/usr/local/go/bin
```

This could be something that I am doing wrong, if you have anythin you would like me to test on my end feel free to let me know.

**Comment by khyberspache** [comment]
@privateducky Yes I know what this is and yes I can fix it.  Remember when I did that refactor of sandcat back in the day to make it a Go Module? This is that.

Theses issues stem from the fact that Go doesn't support relative imports, so when you `go get` this module, the import paths are broken:
```Golang
import (
	"./sockets"
	"./util"
```
needs to be:
```Golang
import (
	"github.com/preludeorg/pneuma/sockets"
	"github.com/preludeorg/pneuma/util"
```

and we need a go.mod.  Gimme a sec I'll post a PR

**Comment by privateducky** [comment]
I knew you'd know!

**Comment by khyberspache** [comment]
@CrimsonK1ng I posted a PR just now to fix it.

**Comment by CrimsonK1ng** [comment]
Sweet! That branch works out of the box for me.
