### ISSUE TITLE
Base64 generated for Obfuscated PSH appears wrong.

### ISSUE THREAD

**Issue by kwadner** [preludeorg/pneuma#84]
I believe this is related to the issue outlines on this [ServerFault post](https://serverfault.com/questions/778123/powershell-executing-base64-commands-returns-error) where the base64 generated is incorrect.

The result output seen for the TTP is:
![image](https://user-images.githubusercontent.com/2546881/131410617-820c290c-8963-4696-bb5d-94749085d54a.png)

Executing this PSH directly, and then with the Base64 encoding method outlined in the ServerFault post can be seen below with the second, different base64, working correctly.

![image](https://user-images.githubusercontent.com/2546881/131410788-3c392e32-a6a6-49af-9321-fb36bf3c0954.png)

**Comment by khyberspache** [comment]
Closing this to centralize bug tracking here: https://github.com/preludeorg/operator-support/issues/328
