### ISSUE TITLE
The cmd executor for Windows is not correctly escaping characers

### ISSUE THREAD

**Issue by WoBuGs** [preludeorg/pneuma#95]
### Issue
It appears that running multiline commands through the cmd executor is not correctly handled by Pneuma:
- Double quotes are not escaped (after testing a bit, this has no real impact)
- Commands after the first line are not processed

For instance, running the following TTP:
```
windows:
    cmd: |
        reg save HKLM\sam C:\Temp\sam
        reg save HKLM\sysem C:\Temp\system
        reg save HKLM\security C:\Temp\security
```
Will produce the following Windows event (sysmon extracts for ID=1):
```
CommandLine: cmd.exe /S /C "reg save HKLM\sam C:\Temp\sam
reg save HKLM\sysem C:\Temp\system
reg save HKLM\security C:\Temp\security"
```
Followed only by:
```
CommandLine: reg save HKLM\sam C:\Temp\sam
```
The other two lines are not executed.

### Root cause
This is due to the use of `fmt.sprintf`, instead of `exec.CommandContext`. I'm no a go expert though, so it is to be confirmed.

My guess would be to use the `exec.CommandContext` for each executor types, as it is currently done for most of them.

### References
- [commands_windows.go](https://github.com/preludeorg/pneuma/blob/master/commands/commands_windows.go#L20)

**Comment by khyberspache** [comment]
@WoBuGs In your yaml file, can you try setting the configuration to look like this, then retest?
```yaml
windows:
    cmd: >
        reg save HKLM\sam C:\Temp\sam &
        reg save HKLM\sysem C:\Temp\system &
        reg save HKLM\security C:\Temp\security
```

**Comment by WoBuGs** [comment]
You're right, with `>`, it should work in this particular example.

I just edited the description to remove the `&` at the end of the first to commands.

The goal here is to support multilines commands for `cmd` (like it is possible with `psh` for example).

**Comment by WoBuGs** [comment]
Indeed, that's the observed behaviour. The comand was taken from this [Atomic Red Team](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1003.002/T1003.002.md#atomic-test-1---registry-dump-of-sam-creds-and-secrets) payload, directly imported into Prelude.

After importing the TTP into Prelude, the command looks like: 
```
windows/cmd:
reg save HKLM\sam C:\Temp\sam &
reg save HKLM\sysem C:\Temp\system &
reg save HKLM\security C:\Temp\security
```

But when sent to a pneuma agent, it is sent as 3 lines instead of 1.

Do you think that when receiving multiline commands for the `windows/cmd` executor, pneuma should merge them into one (with `&` as separator), or that it should be performed by the user (who writes TTPs)?

**Comment by khyberspache** [comment]
I can make Pneuma strip the `\r\n` and `\n` characters, but it's something we've decided internally to not adjust in Operator. We want the TTP file to represent exactly what will get executed (including escape characters).

**Comment by WoBuGs** [comment]
Alright, that's a good stand!

So maybe some adjustment should be done in Operator regarding the parsing of ART payloads that are using `windows/cmd`?

**Comment by khyberspache** [comment]
I'm looking through some of the ART TTPs today.  I think my plan is to explicitly just strip the newline characters from CMD tasks
